apache/mina-sshd

- sshd-core/src/main/java/org/apache/sshd/common/io/DefaultIoServiceFactoryFactory.java
Simple fix is the catch the NPE coming from the updating felix framework. The server seems to be able to gracefully handle this condition.
> SSHD-388 - SSH server fails during bundle update

- sshd-core/src/main/java/org/apache/sshd/common/kex/extension/DefaultClientKexExtensionHandler.java
Unconditionally announce that the client wants to get the server's
SSH_MSG_EXT_INFO. Otherwise the server will never send it. Add the
"ext-info-c" marker only on the very first key exchange proposal,
and make sure the client doesn't send by mistake "ext-info-s".
KexExtensions are available in all phases except PREKEX.
When server-sig-algs is received, reorder the client session's
signature factories such that algorithms the server announced as
supported come first, followed by those not announced, both in client
order.
The client determines the order and the server just says what it
supports.
Note that per RFC 8308 [1] it's possible that a server doesn't announce
_all_ the algorithms it supports, and a client is allowed to try
unsupported algorithms, but may face authentication penalties …
> [SSHD-1141] Fix client-side server-sig-algs handling

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
IBM's Sterling B2B SFTP connector may limit some files to be downloaded
only once. The mechanism they use assumes that once a file has been
opened, it'll be read and closed without any other SFTP requests being
made on the same handle in between.
Get the file size via SSH_FXP_STAT before opening the file instead of
using SSH_FXP_FSTAT on the handle obtained from opening the file. That
way it should be possible to download such files from such an off-spec
SFTP server.
> [SSHD-1147] SftpInputStreamAsync: get file size before SSH_FXP_OPEN

- sshd-core/src/main/java/org/apache/sshd/client/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/extension/DefaultClientKexExtensionHandler.java
If the server had announced via server-sig-algs which signature
algorithms it supports, UserAuthPubKey tries the known algorithms
first. If authentication with such a known signature algorithm fails,
there is no point trying other algorithms.
Trying different signature algorithms may make sense only if the client
doesn't know which algorithms the server supports.
> [SSHD-1141] Pubkey auth: handle failure with known signature algorithm

- sshd-core/src/main/java/org/apache/sshd/common/channel/AbstractChannel.java
When the peer closes the channel, just reply with a CLOSE message.
Do not send an EOF before the CLOSE. See RFC 4254, section 5.3.[1]
[1] https://tools.ietf.org/html/rfc4254#section-5.3
> [SSHD-1158] Don't send channel EOF after having received channel CLOSE

- sshd-common/src/main/java/org/apache/sshd/common/cipher/BaseGCMCipher.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BuiltinCiphers.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/ChaCha20Cipher.java
- sshd-common/src/main/java/org/apache/sshd/common/mac/Poly1305Mac.java
- sshd-common/src/test/java/org/apache/sshd/common/cipher/ChaCha20CipherTest.java
- sshd-core/src/main/java/org/apache/sshd/common/BaseBuilder.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
This uses BouncyCastle due to OpenSSH using the non-RFC variant of ChaCha20 as well as having a direct implementation of Poly1305 (Java 11 does not expose the Poly1305 mac engine).
https://issues.apache.org/jira/browse/SSHD-1017
Some ideas on simplification adapted from https://github.com/mwiede/jsch/pull/17
> [SSHD-1017] Add support for chacha20-poly1305@openssh.com

- sshd-common/src/main/java/org/apache/sshd/common/Property.java
- sshd-core/src/main/java/org/apache/sshd/client/session/AbstractClientSession.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/main/java/org/apache/sshd/core/CoreModuleProperties.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTransferTest.java
There was a window in AbstractSession.requestNewKeyExchange()
during which the KEX state was set already to INIT, but the
caller's proposal not set yet. If the peer had also decided to
start a new key exchange, it was possible that the peer's KEX_INIT
message arrived and was handled in that window and then proceeded
with wrong or uninitialized data.
KEX negotiation must start only when both proposals are indeed
available. Thus wait when having received a KEX_INIT from the peer
until our own proposal has been prepared before continuing with the
negotiation.
> [SSHD-1197] Fix race condition in KEX

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/agent/SshAgent.java
- sshd-core/src/main/java/org/apache/sshd/agent/SshAgentConstants.java
- sshd-core/src/main/java/org/apache/sshd/agent/SshAgentKeyConstraint.java
- sshd-core/src/main/java/org/apache/sshd/agent/common/AbstractAgentProxy.java
- sshd-core/src/main/java/org/apache/sshd/agent/common/AgentDelegate.java
- sshd-core/src/main/java/org/apache/sshd/agent/local/AgentImpl.java
Change the API of SshAgent.addKeyToAgent() to be able to pass key
constraints. Provide default implementations for the documented
OpenSSH constraints: confirm, lifetime, and the sk-provider extension.
Handle them in the AbstractAgentProxy implementation. Note that
AbstractAgentProxy currently implements addKeyToAgent() only for
OpenSSH. Users wanting to support a different agent may have to
implement different constraints by extending the provided base classes,
and may have to provide their own SshAgent (and a factory for it)
implementing a different protocol for addKeyToAgent().
> [SSHD-1221] Support key constraints when adding a key to the SSH agent

- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/BufferUtils.java
- sshd-core/src/main/java/org/apache/sshd/client/kex/DHGClient.java
- sshd-core/src/main/java/org/apache/sshd/common/BaseBuilder.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/AbstractDH.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/ECDH.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/MontgomeryCurve.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/XDH.java
- sshd-core/src/main/java/org/apache/sshd/server/kex/DHGServer.java
- sshd-core/src/test/java/org/apache/sshd/DefaultSetupTestSupport.java
This adds support for curve25519-sha256 (and its libssh version) along with curve448-sha512. These key exchange methods are supported for both Java 11 and Bouncy Castle.
https://issues.apache.org/jira/browse/SSHD-704
https://tools.ietf.org/html/rfc8731
https://tools.ietf.org/html/rfc7748 (for the X25519/X448 algorithms)
> [SSHD-704] Add support for RFC 8731

- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoAcceptor.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoConnector.java
The hard-coded logger is overly verbose by default. Change the log level to TRACE and propagate class identity, so that Logger implementations can correctly enable/disable the messages. Also share a single LoggingHandler for all channels, reducing memory footprint.
> [SSHD-1230] Log netty channel traffic on TRACE level

- sshd-core/src/main/java/org/apache/sshd/client/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/test/java/org/apache/sshd/client/auth/pubkey/InvalidRsaKeyAuthTest.java
Reset the list when a new key is tried to avoid that we inadvertently
try a remaining signature algorithm from a previous failed
authentication attempt.
> [SSHD-1231] Pubkey auth: reset list of signature algorithms

- sshd-core/src/main/java/org/apache/sshd/client/session/AbstractClientSession.java
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientSessionImpl.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/CurrentService.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/SessionHelper.java
- sshd-core/src/main/java/org/apache/sshd/server/session/AbstractServerSession.java
Previous code declared a `SessionHelper.sessionLock` and used it in
`AbstractSession` around `doHandleMessage()` and in `ClientSessionImpl`
to partially guard service-related info (the service names and the next
service) against concurrent accesses.
The use of this `sessionLock` around handling messages was a way to
synchronize access to the `currentService` field.
Encapsulate the current service in a synchronized per-session
`CurrentService` object. In `ClientSessionImpl`, install a customized
object that also can handle switching the service (from authentication
to connections), and set the `initialRequestSent` flag atomically.
Message handling is serialized per session already via the `decodeLock`.
Remove the locking in `AbstractSession.handleMessage()`.
Note that like previous code …
> Clean up service support

- CHANGES.md
- README.md
- sshd-common/src/main/java/org/apache/sshd/common/kex/extension/parser/HostBoundPubkeyAuthentication.java
- sshd-core/src/main/java/org/apache/sshd/client/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/extension/DefaultClientKexExtensionHandler.java
- sshd-core/src/test/java/org/apache/sshd/client/auth/pubkey/HostBoundPubKeyAuthTest.java
- sshd-core/src/test/resources/org/apache/sshd/client/auth/pubkey/entrypoint.sh
- sshd-mina/pom.xml
- sshd-netty/pom.xml
Provide a KexExtensionParser for it; make the default client KEX
extension handler understand the "publickey-hostbound@openssh.com"
extension, and use it in UserAuthPublicKey.
The extension changes the auth name in the SSH_MSG_USERAUTH_REQUEST
from "pubkey" to "publickey-hostbound-v00@openssh.com" and includes
the server's public key in the message.
See https://github.com/openssh/openssh-portable/blob/807be686/PROTOCOL#L347
> [SSHD-1254] Client side implementation of host bound pubkey auth

- CHANGES.md
- README.md
- docs/technical/global_requests.md
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientConnectionService.java
- sshd-core/src/main/java/org/apache/sshd/common/future/GlobalRequestFuture.java
- sshd-core/src/main/java/org/apache/sshd/common/session/Session.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/test/java/org/apache/sshd/common/session/GlobalRequestTest.java
Handling of global requests with want-reply=true was synchronous. This
is fine if the call is made on a non-I/O thread, but to be able to use
global requests in I/O threads, an asynchronous handling is needed.
Provide an asynchronous variant of Session.request() that returns a
future and that takes an optional reply handler as argument. If a
handler is given, it will be invoked by the framework once the reply
is received, on the I/O thread that received the reply. The future can
in this case be used to wait until the request has indeed be sent.
Without handler, the future can be used to await the reply on some
other thread, or to handle it via a future listener.
This makes global request handling much more flexible, avoids that a
synchronous implementation blocks an I/O thread, and it …
> Asynchronous handling of global requests

- pom.xml
- sshd-core/src/main/java/org/apache/sshd/common/forward/DefaultForwarder.java
- sshd-core/src/main/java/org/apache/sshd/server/forward/TcpipServerChannel.java
TCP/IP forwarding: always resume reading, even in error cases
PortForwardingTest did hang sometimes in GitHub CI (Windows/Java 1.8).
Also: don't redirect test output to a file; these files are not
accessible once a GitHUb CI pod has terminated. By not redirecting,
the GitHUb CI build log has much more information useful to analyze
potential problems.
> Fix hang in PortForwardingTest

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Connector.java
If there's an exception in Nio2Connector after the session was set on
the DefaultIoConnectFuture, a program might just hang on that session
until the next read or write attempt, or until a timeout expired.
This was caused by closing the underlying connection, but not properly
closing the already existing session, and because the session was
already set on the future, setting the exception had no effect anymore.
Fix this by immediately closing the Nio2Session properly in that case.
> [SSHD-1281] Close Nio2Session properly on failure after connecting

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/KeyExchangeMessageHandler.java
Make sure that a thread does not try to acquire the write lock if
it already holds the read lock. This could happen if a write is not
enqueued and there is an exception during writing, and we then try
to close the session on the same thread.
The read/write lock is used for three purposes: first, it gives the
flushing thread trying to empty the queue of pending packets priority
over other threads trying to enqueue more packets, and second, it is
held during writeOrEnqueue() while writing a packet directly to prevent
that the KEX state changes between being checked and the write being
done, and third, to prevent that the KEX state changes asynchronously
while the flushing thread is checking it. The read/write lock itself
does not serve to ensure mutual exclusion on the KEX state itself. …
> [SSHD-1289] Fix lock handling in KeyExchangeMessageHandler

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
If data is appended while a file is read via SFTP, SftpInputStreamAsync
would enter an infinite loop if requestOffset >= fileSize + bufferSize.
Fix this and issue only sequential read requests once we detect that
we're beyond the expected EOF.
> [SSHD-1288] SFTP: fix reading files that are being written

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
More precise logging in onWritten() to distinguish the cases better.
> [SSHD-1290] ChannelAsyncOutputStream: improve logging

- CHANGES.md
- sshd-mina/src/main/java/org/apache/sshd/mina/MinaServiceFactory.java
- sshd-mina/src/test/java/org/apache/sshd/mina/MinaSessionTest.java
Ensure that the IoProcessor pool is disposed, otherwise a selector may not get closed, leading to a file handle leak.
> [SSHD-1294] Close MinaServiceFactory instances properly

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/session/forward/ExplicitPortForwardingTracker.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/PortForwardingTest.java
This fixes de-allocating / unbinding a local port forwarding binding when using a dynamic auto-allocated port.
The information "localAddress" is controlled by the user and may contain still a port `0` which means auto-allocating a local port; the actual local port is available in 'boundAddress". However, "DefaultForwarder" tracks
the actual port mappings only.
I have run the tests locally with a Java 8 without issues.
Related issue https://issues.apache.org/jira/browse/SSHD-1293
I also added an additional commit modifying the test covering the missing signal. If you are fine with this, I'd squash them. Or maybe as an additional test?
> [SSHD-1293] Fix unbinding port forwarding for auto-alloc port

- .github/workflows/master-build.yml
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
- sshd-core/src/main/java/org/apache/sshd/server/channel/ChannelSession.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/PortForwardingTest.java
Window expansions can occur even when the channel is already closing. Abort writing only if the stream is closed immediately, or is already closed.
> ChannelAsyncOutputStream: fix closing gracefully

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/KeyUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-common/src/test/java/org/apache/sshd/common/config/keys/KeyUtilsTest.java
- sshd-common/src/test/java/org/apache/sshd/common/util/buffer/BufferTest.java
Avoid OOMEs when reading from a Buffer when the key length is out of bounds, and provide a utility method to read a public key file.
> [SSHD-1297] Improvements for reading public keys

- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/ApacheServerJSchClientTest.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/PortForwardingLoadTest.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/PortForwardingTest.java
- sshd-core/src/test/java/org/apache/sshd/util/test/JSchUtils.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoSession.java
JSch use interrupts internally for synchronization, but has a race condition that may result in the interrupt actually interrupting client code.
Netty may deliver multiple read events for a single iteration of its event loop. accumulate the data and deliver it once the low-level socket read is complete.
Note that this buffer is not unbounded; it is bounded by the underlying socket buffer.
> Bug fixes: Work-around a JSch bug, and fix Netty reading from a socket

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/channel/AbstractClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
- sshd-core/src/main/java/org/apache/sshd/core/CoreModuleProperties.java
- sshd-core/src/main/java/org/apache/sshd/server/channel/ChannelSession.java
- sshd-core/src/main/java/org/apache/sshd/server/forward/TcpipServerChannel.java
- sshd-core/src/test/java/org/apache/sshd/WindowAdjustTest.java
- sshd-core/src/test/java/org/apache/sshd/common/channel/ChannelAsyncOutputStreamTest.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/SftpModuleProperties.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/DefaultSftpClient.java
Remove the option not to send a chunk when the remote window is smaller than the packet size, and we're trying to write more than the remote widow size bytes. This option may lead to hangs with peers that wait with sending their window adjustment until the window size is very low, or even zero.
RFC 4254 does not mandate any particular point at which an SSH implementation should send a window adjustment. Implementations doing so only once the window has been fully consumed are well within the bounds of the specification.
Therefore remove this option altogether, and always send some data if the window size is > 0. Refactor the writePacket() method to make it much simpler and clearer.
Client options removed:
* SftpModuleProperties.CHUNK_IF_WINDOW_LESS_THAN_PACKET
* …
> [SSHD-1173] Simplify writing in ChannelAsyncOutputStream

- sshd-common/src/main/java/org/apache/sshd/common/io/IoReadFuture.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/AbstractClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncInputStream.java
- sshd-core/src/test/java/org/apache/sshd/client/session/ClientSessionTest.java
If a channel's error stream has been redirected to the output stream, return null streams from getAsyncErr() and getInvertedErr(). Since they are redirected, application code should never see any data on them.
Also document the IoReadFuture better, and change the single implementation of that interface to match. While the future is not done, operations return null or zero. EOF is signaled by getRead() == -1, or getException() returning an EOFException.
> [SSHD-1303] AbstractClientChannel: use null stream for redirected stderr

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/channel/AbstractClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/ClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelPipedInputStream.java
- sshd-core/src/test/java/org/apache/sshd/client/session/ClientSessionTest.java
- sshd-core/src/test/java/org/apache/sshd/common/channel/ChannelPipedInputStreamTest.java
Closing them when the channel closes leads to the strange situation that the application reads from an already closed InputStream. That's not a good idea.
It's the caller's responsibility to close the input stream obtained from Channel.getInvertedOut() or getInvertedErr(). And of course it should do so only after it has read all the data it wanted, and the channel is closed.
It's not a real problem if the stream is not closed (for instance, if the application never even called getInvertedOut() and never read anything). Closing doesn't do much anyway except awaking a potentially waiting read() call. Moreover, if the channel is short-lived and didn't transmit a lot of data, the application may well start reading from the stream only after the underlying SSH channel is already closed.
One …
> [SSHD-1302] AbstractClientChannel: don't close inverted output streams

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Session.java
Nio2Session.shutdownOutputStream() can be invoked while there are still writes in progress. The output is shut down in TCP/IP port forwarding to propagate an SSH_MSG_CHANNEL_EOF from the channel to whatever is on the other side of the forwarded port; see SSHD-1055. However, writing through the socket is asynchronous, so a channel may get the following sequence of events:
1. receive last SSH_MSG_CHANNEL_DATA
2. Nio2Session.writeBuffer() enqueues the write request
3. SSH_MSG_CHANNEL_DATA handling completes
4. receive SSH_MSG_CHANNEL_EOF
5. call Nio2Session.shutdownOutputStream()
If (5) shuts down the output immediately but the write request from (2) has not been written yet, that write attempt will fail with a ClosedChannelException.
The output stream on the socket should not be shut down …
> [SSHD-1307] Make Nio2Session.shutdownOutputStream() asynchronous

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
Use the local window's packet size for reading, and the remote window's packet size for writing (both minus a bit for protocol overhead) as the default SFTP buffer size.
Fix SftpInputStreamAsync to also work for buffer sizes greater than twice what the server will ever return. Previously, the stream read data from the wrong offset in that case.
> [SSHD-1287] SFTP: better default buffer size handling

- sshd-core/src/main/java/org/apache/sshd/common/channel/BufferedIoOutputStream.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
Don't try to write a future that's already done in startWrite(). Just skip it and try the next one, if any.
Fixes #263.
Bug: https://github.com/apache/mina-sshd/issues/263
> GH-263: Fix race condition in BufferedIoOutputStream

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelPipedOutputStream.java
- sshd-core/src/test/java/org/apache/sshd/common/channel/ChannelPipedOutputStreamTest.java
- sshd-scp/pom.xml
GH-266: Make ChannelPipedOutputStream.flush() a no-op
ChannelPipedOutputStream passes on data immediately to its sink.
Flushing such a stream is thus a no-op, and must not throw an
exception even when the stream is already closed. Otherwise there
may be spurious failures if the reader of the sink decides to
close the whole channel before the channel has flushed the
ChannelPipedOutputStream.
Fixes #266.
Bug: https://github.com/apache/mina-sshd/issues/266
> Investigate flaky tests

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientConnectionService.java
- sshd-core/src/main/java/org/apache/sshd/common/future/GlobalRequestFuture.java
- sshd-core/src/main/java/org/apache/sshd/common/global/GlobalRequestException.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/test/java/org/apache/sshd/KeepAliveTest.java
- sshd-core/src/test/java/org/apache/sshd/common/session/GlobalRequestTest.java
If a reply is requested, but none arrives within the timeout, throw an
exception and terminate the connection.
This rolls back the changes made in ClientConnectionService in commit
de2f8fef2e. It's quite all right to use the synchronous implementation of
Session.request() because heartbeats are not sent from I/O threads.
However, commit de2f8fef2e broke the contract specified in interface
Session, which says Session.request() must return "the buffer if the
request was successful, `null` otherwise." The implementation from
commit de2f8fef2e threw an exception instead.
This was wrong, and is corrected now in this commit. Note that this
means that a caller cannot distinguish between the server replying
SSH_MSG_UNIMPLEMENTED or SSH_MSG_REQUEST_FAILURE.
Where such distinction is needed, use an …
> GH-268: Fix ClientConnectionService.sendHeartBeat()

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/extensions/helpers/AbstractSftpClientExtension.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/DefaultSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpStatus.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/impl/SftpStatusTest.java
Treat the error message and the language tag as optional. It appears that there are SFTP v3 servers that send status records without these fields. Also improve the client-side logging of SFTP requests and responses.
Fixes #275.
> SFTP: parsing of SSH_FXP_STATUS

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/extensions/helpers/AbstractSftpClientExtension.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/DefaultSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpOutputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpResponse.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpStatus.java
Introduce an SftpResponse abstraction to centralize basic reply buffer parsing and validation.
> SFTP: Refactor to reduce code duplication

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/threads/CloseableExecutorService.java
`ExecutorService` implements `AutoCloseable` in Java 19 and provides a default method for `close()`. This conflicts in `CloseableExecutorService`, which mixes in `org.apache.sshd.common.Closeable`, which has its own default method for `close()`.
As a minimum fix add overrides of `close()` as needed, explicitly calling the Apache MINA sshd variant of `close()`.
Fixes #285.
> GH-285: Fix compilation failure on Java 19

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/server/keyprovider/AbstractGeneratorHostKeyProvider.java
Apparently it is possible on Windows that the ACL for a file have no entry for the file owner. (Typically the owner is then member of a group, and there is an entry for the group.) The previous code would in such cases remove all access permissions from all entries, resulting in a file that even the owner could no longer access.
Change the logic: not only remove all permissions for non-owner entries but also add an explicit entry for the owner, giving it full access permissions.
Fixes #282.
> GH-282: Fix ACL for host key file on Windows

- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-core/src/main/java/org/apache/sshd/client/auth/keyboard/UserAuthKeyboardInteractive.java
- sshd-core/src/main/java/org/apache/sshd/server/auth/keyboard/UserAuthKeyboardInteractive.java
With trace logging on, sensitive data in keyboard-interactive or in password user authentication ended up being logged via two paths both in a client or in a server.
In a client:
- when logging outgoing packets just before they are encrypted
- when logging challenge responses in keyboard-interactive auth
In a server:
- when logging incoming packets just after having been decrypted
- when logging received challenge responses (keyboard-interactive auth)
Avoid this by not logging raw packet contents for
SSH_MSG_USERAUTH_REQUEST and SSH_MSG_USERAUTH_INFO_RESPONSE. In the client, log challenge responses with echo=false as "(hidden)", and in the server don't log the received challenge responses at all, only their number.
All these log messages are active only for trace logging, which is …
> [SSHD-1315] Improve logging

- sshd-core/src/main/java/org/apache/sshd/agent/local/AgentForwardedChannel.java
- sshd-core/src/main/java/org/apache/sshd/agent/unix/AgentForwardedChannel.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/AbstractClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/ChannelDirectTcpip.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncInputStream.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelPipedInputStream.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/LocalWindow.java
- sshd-core/src/main/java/org/apache/sshd/common/forward/ChannelToPortHandler.java
- sshd-core/src/main/java/org/apache/sshd/server/channel/ChannelSession.java
- sshd-core/src/main/java/org/apache/sshd/server/x11/ChannelForwardedX11.java
- sshd-core/src/test/java/org/apache/sshd/util/test/AsyncEchoShellFactory.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpSubsystem.java
The previous implementation would always reset the window to the maximum size when it had dropped to below half the maximum size.
This was wrong and defeated the purpose of having a window. The window size is reduced upon reception of the data, and incremented when the reader from the channel has read some data. With a slow reader and a fast sender, the window would be opened fully even if the reader had not read the previously accumulated data. As a result, internal buffers could exceed the window size by a lot.
(Consider the very good description in ChannelDataReceiver: if the exit toll booth always tells the entry the bridge was free again, far too many cars would be let onto the bridge. With a real bridge, there'd be a gigantic traffic jam; with Apache MINA sshd, the bridge (the …
> Fix the channel window logic

- sshd-common/src/main/java/org/apache/sshd/common/keyprovider/MultiKeyIdentityProvider.java
- sshd-core/src/main/java/org/apache/sshd/client/SshClient.java
- sshd-core/src/test/java/org/apache/sshd/client/ClientTest.java
Automatically configure KeyIdentityProviders to use the FilePasswordProvider set on the client if they don't have an explicit password provider already.
This simplifies setting up a client to deal with encrypted private keys: set a FilePasswordProvider on the client, and set a FileKeyPairProvider with the key file(s), and off it goes.
Previously, setting a FilePasswordProvider on an SshClient only had an effect for identity files specified in a HostConfigEntry. For other use cases, a FilePasswordProvider had to be set explicitly on the FileKeyPairProvider. (Which is still possible, and takes precedence over the new auto-configuration.)
This also makes it possible to use SshClientMain with an encrypted private key given on the command-line via the -i option.
Fixes #297.
> GH-297: SshClient: auto-configure for encrypted key identities

- sshd-core/src/main/java/org/apache/sshd/server/session/AbstractServerSession.java
- sshd-core/src/test/java/org/apache/sshd/server/ServerTest.java
Services need to be started. In particular, the connection service starts its heartbeat, if configured, when started. It was already noticed in commit e74e2041 that the server-side did not start services, but at that time the effect was not recognized because tests were too unstable back then. A test for server-side heartbeats was also missing.
Fixes #298.
> GH-298: Start service in AbstractServerSession

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractConnectionService.java
- sshd-core/src/test/java/org/apache/sshd/client/channel/ChannelExecTest.java
Fix reading the id from the message, and add a test in which the server uses artificially high channel IDs beyond Integer.MAX_VALUE.
Fixes #300.
> GH-300: SSH_MSG_CHANNEL_OPEN_CONFIRMATION: channel ID is unsigned

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/auth/keyboard/UserAuthKeyboardInteractive.java
- sshd-core/src/main/java/org/apache/sshd/client/auth/password/UserAuthPassword.java
- sshd-core/src/main/java/org/apache/sshd/core/CoreModuleProperties.java
- sshd-core/src/test/java/org/apache/sshd/client/ClientTest.java
- sshd-core/src/test/java/org/apache/sshd/common/auth/PasswordAuthenticationTest.java
GH-283: Fix handling of CoreModuleProperties.PASSWORD_PROMPTS
The setting was not considered in password authentication, and in
keyboard-interactive authentication counted the number of non-empty
challenges, which could lead to an extra authentication request
message to be sent, or to keyboard-interactive authentication being
aborted too early.
The property is supposed to correspond to the OpenSSH configuration
NumberOfPasswordPrompts, which despite the name counts not the number
of prompts but the number of times password or keyboard-interactive
authentication is attempted. For password authentication, this is
the same (if one ignores possible password-change requests), but in
keyboard-interactive authentication, there may be several prompts
per attempt.
Fix the implementation in Apache …
> GH-283: Fix handling of CoreModuleProperties.PASSWORD_PROMPTS

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
If a client uses an SFTP buffer size greater than the maximum amount of data the server is willing to return for an individual read request, data will be delivered with "holes". For instance, if the server limit is 63kB, and the client uses a buffer size of 64kB, it will issue requests to read 64kb at offset 0, then 64kB at offset 65536, and so on. But it will get only 63kB at offset 0 and 63kB at offset 65536. When it notices that, it'll request the missing 1kB at offset 64512 synchronously.
In a large file, this can lead to jumping back and forth in the file frequently if the client issues new requests after having read missing data, because the very next read again will be short, but the server may have already skipped forward again to satisfy the new requests.
Avoid that by not …
> GH-293: Handle SFTP buffer sizes > server limit better

- pom.xml
SSHD-Mina seems to be compatible with slf4j 1.7.x and 2.0.x. At least my local build (`mvn clean verify`) succeed without errors. I only had to disable the license check for slf4j.api.
Please let me know if my assumption about compatibility in regards of slf4j-2 is wrong.
This PR adjusts the OSGi `Import-Package` entries in the MANIFEST.MF to make sshd-mina work with both versions of the slf4j.api bundle in an OSGi runtime.
> Adapt OSGi metadata of sshd.osgi to work with slf4j-api 1 and 2

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpFileSystemTest.java
Files.delete() is specified *not* to follow symbolic links. The implementation in SftpFileSystemProvider checked for write access and file existence via a method that does resolve symbolic links. This lead to general inconsistency and various kinds of failures.
Fix this by making sure that the code does not resolve symbolic links in Files.delete().
Fixes #325.
> GH-325: SFTP: fix deleting remote symbolic links

- pom.xml
Instead of the 'maven-bundle-plugin:cleanVersions' goal, use BND-lib's range macro:
https://bnd.bndtools.org/macros/range.html
@tomaswolf maybe you are interested in this as well?
> Simplify maven-bundle-plugin configuration

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/loader/pem/PKCS8PEMResourceKeyPairParser.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/Ed25519PEMResourceKeyParser.java
Older OpenSSL could encode ed25519 private keys as PEM with traditional RFC 1421/1423 encryption (using "Proc-Type" and "DEK-Info" headers) and used the label "ED25519 PRIVATE KEY" in such PEM files.
> Read openssl ed25519 PEM with traditional encryption

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/client/config/hosts/HostConfigEntry.java
- sshd-common/src/main/java/org/apache/sshd/client/config/hosts/HostPatternsHolder.java
- sshd-common/src/test/java/org/apache/sshd/client/config/hosts/ConfigFileHostEntryResolverTest.java
- sshd-common/src/test/java/org/apache/sshd/client/config/hosts/HostConfigEntryTest.java
- sshd-core/src/test/java/org/apache/sshd/client/config/hosts/HostConfigEntryResolverTest.java
This change tries to bring config file processing more in line with the semantics indicated in the ssh man page. The most significant changes are that each attribute is drawn from the first matching entry in file order. There are also defaults supplied that are in line with the behavior of the ssh command line tool. In particular, the local user name is used for any host where none is specified, and port 22 is used whenever port is not specified. Even though one might imagine these obvious defaults were in effect before, there were paths through the code where they did not get set.
This change modifies some of the test cases:
testResolvePort, testResolveUsername -- Removed because these functions no longer exist.
testFindBestMatch -- Removed because that's not how config files are …
> Follow first-match semantics specified for ssh config file

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/agent/common/AbstractAgentClient.java
- sshd-core/src/test/java/org/apache/sshd/agent/AgentUnitTest.java
Respect the flags in OpenSSH signing requests. These flags tell what kind of signature should be produced for an RSA key: ssh-rsa, rsa-sha2-256, or rsa-sha2-512.
Previous code code only set the flags on the client side, but ignored them in the server side and thus always answered with a ssh-rsa signature.
Fixes #364.
> GH-364: Use flags for RSA signature requests in AbstractAgentClient

- sshd-common/src/main/java/org/apache/sshd/common/util/net/SshdSocketAddress.java
If you currently connect to an host ip string, the known_hosts lookup is done with the reverse dns entry.
`getHostString` keeps the IP.
> Remove unwanted reverse lookup

- sshd-common/src/main/java/org/apache/sshd/common/file/root/RootedDirectoryStream.java
- sshd-common/src/main/java/org/apache/sshd/common/file/root/RootedFileSystem.java
- sshd-common/src/main/java/org/apache/sshd/common/file/root/RootedFileSystemProvider.java
- sshd-common/src/main/java/org/apache/sshd/common/file/root/RootedFileSystemUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/file/root/RootedSecureDirectoryStream.java
- sshd-common/src/main/java/org/apache/sshd/common/file/util/BaseFileSystem.java
- sshd-common/src/main/java/org/apache/sshd/common/util/io/IoUtils.java
- sshd-common/src/test/java/org/apache/sshd/common/file/root/RootedFileSystemProviderTest.java
- sshd-common/src/test/java/org/apache/sshd/common/util/io/IoUtilsTest.java
- sshd-common/src/test/java/org/apache/sshd/util/test/CommonTestSupportUtils.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/AbstractSftpSubsystemHelper.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpFileSystemAccessor.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpSubsystem.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpVersionsTest.java
- More unix like
- Symlinks improvements
> [SSHD-1324] Rooted file system can leak informations

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
We keep the top-level future of the last initiated write to be able to delay closing the stream until it has been written. But once the write _has_ been done, there is no need to keep the future still referenced.
Use a listener on the future to set lastWrite to null if it still references the same future.
> [SSHD-1327] ChannelAsyncOutputStream: remove write future when done

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/io/FileSnapshot.java
- sshd-common/src/main/java/org/apache/sshd/common/util/io/ModifiableFileWatcher.java
- sshd-common/src/test/java/org/apache/sshd/client/config/hosts/ConfigFileHostEntryResolverTest.java
- sshd-common/src/test/java/org/apache/sshd/client/config/keys/ClientIdentityFileWatcherTest.java
- sshd-common/src/test/java/org/apache/sshd/common/util/io/ModifiableFileWatcherTest.java
- sshd-core/src/test/java/org/apache/sshd/server/config/keys/AuthorizedKeysAuthenticatorTest.java
Additionally, handle the case of files being modified very quickly, such that the last modified timestamp doesn't change, even though the file was modified. If the modification did not change the file size, such metadata is "racily clean", meaning it indicates the file had not been modified when in fact it was.
This can occur because of the finite resolution of file timestamps. If the file timestamp has a granularity of 2 seconds (FAT), two file modifications within these two seconds that don't change the file size cannot be recognized.
Hence any file timestamp from the past 2 seconds (measured from the time it was read) is suspect, and the file must be considered potentially modified, and must be re-loaded.
This is not a problem unless one frequently writes files and then reads them …
> GH-370: Also compare file keys in ModifiableFileWatcher

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystem.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpFileSystemTest.java
A SftpFileSystem can be obtained in two ways:
1. Via FileSystems.newFileSystem()
2. Via SftpClientFactory.instance().createSftpFileSystem(ClientSession)
In the first case, the SftpFileSystemProvider automatically creates a ClientSession, and that session must be closed when the file system closes.
In the second case, user code already has a ClientSession and wants to run an SftpFileSystem within. In this case, the session _must not_ be closed when the file system closes.
Add a session attribute that can be set on a ClientSession to tell the SftpFileSystem whether it owns the ClientSession. The SftpFileSystem will close only owned sessions.
Also add a SessionListener to ensure the file system is closed when the session closes.
Bug: https://issues.apache.org/jira/browse/SSHD-1310
> [SSHD-1310] SftpFileSystem: do not close user sessions

- .github/workflows/build.yml
- .github/workflows/master-build.yml
Split the single workflow into two workflows: a build workflow that compiles and tests and that runs on PRs and that can be called from master-build, which additionally deploys snapshots.
That way we never have to worry about a PR build inadvertently trying to deploy.
> GH-356: Modularize Github workflows

- CHANGES.md
- docs/sftp.md
- docs/technical/sftp_filesystem.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/SftpModuleProperties.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpDirectoryStream.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystem.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpPathIterator.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpIterableDirEntry.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpDirectoryScannersTest.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/server/SftpServerTest.java
The previous implementation always put unused SftpClients back into the pool, but SftpClients in the pool were never closed (unless the whole SSH session was closed).
Let this pool work more like a Java thread pool: besides a maximum size, give it a minimum "core" size, and a maximum life time for idle channels in the pool, and remove them from the pool and close them when they expire. By default, the maximum pool size is 8, the core size 1, and the idle life time 10 seconds.
Also drain the pool when the file system closes, and close all channels.
Remove the ThreadLocal. This mechanism was questionable anyway; it was the source of multiple earlier bug reports and there are some scenarios that it just cannot handle correctly. This change will mean that an application using more threads on …
> GH-371: Re-implement the channel pool of an SftpFileSystem

- docs/technical/sftp_filesystem.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystem.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemAutomatic.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemClientSessionInitializer.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpFileSystemTest.java
When an SftpFileSystem is obtained via FileSystems.newFileSystem(URI), the new file system is created with an implicit SshClient and a new implicit ClientSession. This session has a heartbeat set to keep it open for the lifetime of the file system, i.e., until the file system is closed.
But heartbeats do not guarantee that the session remains open. A server may decide all the same to close the session, for instance, if it is idle for too long. (Even despite heartbeat messages.)
So ensure that in such a case, the file system automatically tries to open a new session. Otherwise a client of such an SftpFileSystem must be prepared to deal with these cases at any time, which may be difficult or even impossible to do.
> SftpFileSystem: keep a session until the filesystem is closed

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/AbstractSftpFilesSystemSupport.java
According to [upstream javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#open-java.nio.file.Path-java.util.Set-java.nio.file.attribute.FileAttribute...-), the default mode is READ (only) when there is no mode specified:
> The [READ](https://docs.oracle.com/javase/8/docs/api/java/nio/file/StandardOpenOption.html#READ) and [WRITE](https://docs.oracle.com/javase/8/docs/api/java/nio/file/StandardOpenOption.html#WRITE) options determine if the file should be opened for reading and/or writing. If neither option (or the [APPEND](https://docs.oracle.com/javase/8/docs/api/java/nio/file/StandardOpenOption.html#APPEND) option) is contained in the array then the file is opened for reading
SftpFileSystemProvider used `READ, WRITE` which leads to `Permission denied` …
> READ (only) default mode in SftpFileSystemProvider.newFileChannel()

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/SftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpRemotePathChannel.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/FileHandle.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpSubsystem.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/AbstractSftpFilesSystemSupport.java
Two commits:
* Tighten rules about `StandardOpenOption`s when creating file channels or input/output streams. Fixes #383.
* Use correct lock modes for `FileChannel.lock(...)`. Fixes #384.
> SftpFileSystem: Open Modes & FileChannel locks

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/client/config/hosts/HostConfigEntry.java
- sshd-common/src/test/java/org/apache/sshd/client/config/hosts/ConfigFileHostEntryResolverTest.java
Resolve ~ and some %-placeholders in file names. This was inadvertently removed in commit c11bfcca.
> [SSHD-1332] Resolve file names in HostConfigEntryResolver

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
Only return EOF once the EOF indicator is set *and* there is no more buffered data.
Fixes #398.
> GH-398: SftpInputStreamAsync: fix EOF for read length zero

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/AbstractChannel.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/exception/SshChannelInvalidPacketException.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/SftpModuleProperties.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/AbstractSftpSubsystemHelper.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/Handle.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpSubsystem.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/server/HandleTest.java
* Work-around for the WS_FTP bug
* Ensure file handle size is indeed the configured number of bytes
* Change default to 4 bytes, and use a different way to generate 4-byte handles
> Fix SFTP file handles

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/io/der/DERWriter.java
- sshd-common/src/main/java/org/apache/sshd/common/util/io/output/NoCloseOutputStream.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
The default implementation calls write(int) for every byte, which may be very inefficient. Override it in the few cases where we use a FilterOutputStream to pass through the operation to the underlying OutputStream, which is also responsible for any index and length validations.
Fixes #407.
> GH-407: Override FilterOutputStream.write(byte[], int, int)

- pom.xml
- sshd-core/pom.xml
- sshd-git/pom.xml
Remove unnecessary version overrides; use the versions pinned in the parent POM. Bump plexus-archiver to 4.8.0 to mitigate CVE-2023-37460.
> Use Apache parent POM 30

- docs/extensions.md
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-contrib/pom.xml
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/ProxyProtocolV2Acceptor.java
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/data/AddressData.java
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/data/FamilyAndTransport.java
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/data/VersionAndCommand.java
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/exception/ProxyProtocolException.java
- sshd-contrib/src/main/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/utils/ProxyUtils.java
- sshd-contrib/src/test/java/org/apache/sshd/contrib/server/session/proxyprotocolv2/ProxyProtocolV2AcceptorTest.java
Proposed implementation for PROXY Protocol V2 for use in SSHD.
> Add support for Proxy Protocol V2

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/channel/ChannelSession.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/AbstractChannel.java
- sshd-core/src/main/java/org/apache/sshd/common/forward/TcpipClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/server/forward/TcpipServerChannel.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/DefaultSftpClient.java
When a channel using a ChannelAsyncOutputStream, do not only wait until all pending data has been written but also wait for the EOF having been sent before proceeding with closing the channel.
For channels using a synchronous ChannelOutputStream, no local fix was found. Instead give the channel access to the IoWriteFuture for sending the EOF packet, and if one was sent, ensure that closing the channel proceeds only after the EOF has been sent.
Otherwise there may be a race between sending that EOF and sending the CLOSE, and sometimes the EOF might be sent after the CLOSE.
Fixes: #410
> GH-410: Ensure EOF gets sent before CLOSE when Channel closes

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/KeyExchangeMessageHandler.java
- sshd-core/src/test/java/org/apache/sshd/client/ClientTest.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/server/SftpServerTest.java
During KEX we may queue up higher-level packets. When KEX ends, we flush this queue, writing all these queued packets. When writing a queued packet fails, previous code handled the failure wrongly, leading to an inconsistent state that could cause an endless loop in writeOrEnqueue.
Fix this by making sure that (a) kexFlushed is true also in this case, and (b) by fulfilling the kexFlushedFuture and closing the session outside of the critical region.
Because kexFlushed = true now also on failure, drain the queue and set up all the queued futures such that they will be fulfilled with the exception.
Additionally, do the same if the session closes while we're still flushing queued packets.
Fixes #414.
> GH-414: Correct error handling in KeyExchangeMessageHandler

- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Acceptor.java
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Connector.java
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2ServiceFactory.java
This allows client code to override and extend the Nio2Session class. Current implementation creates createWriteCycleCompletionHandler which executes OS callback and completes the future on another thread. The overridden implementation may wrap the callbacks with custom code and set up, for example, the logging MDC
> Create Nio2Session using Nio2ServiceFactory

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-core/src/main/java/org/apache/sshd/agent/common/AbstractAgentProxy.java
- sshd-core/src/main/java/org/apache/sshd/client/global/OpenSshHostKeysHandler.java
- sshd-core/src/main/java/org/apache/sshd/common/global/AbstractOpenSshHostKeysHandler.java
- sshd-core/src/test/java/org/apache/sshd/common/global/OpenSshHostKeysHandlerTest.java
Change `Buffer.getPublicKey()` to set the read position to after the key even if reading the key fails. This enables us to continue reading keys from a list of keys in a buffer even when a particular key cannot be decoded.
Change the two places where we receive lists of public keys from external sources: from an SSH agent or via the "hostkeys-00@openssh.com" extension. Skip and log keys that cannot be decoded.
Fixes #434.
> GH-434: skip unknown public keys from external sources

- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/KeyExchangeMessageHandler.java
fixes #458
Threads will expire after 60 seconds.
> Use a singleton threadpool for kex message handler flushing

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BaseCBCCipher.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BaseCTRCipher.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BaseCipher.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BaseRC4Cipher.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BuiltinCiphers.java
- sshd-common/src/main/java/org/apache/sshd/common/cipher/Cipher.java
- sshd-common/src/test/java/org/apache/sshd/common/cipher/BaseCipherResetTest.java
- sshd-common/src/test/java/org/apache/sshd/common/cipher/BaseCipherTest.java
- sshd-core/src/test/java/org/apache/sshd/common/cipher/OpenSshCipherTest.java
- sshd-mina/pom.xml
- sshd-netty/pom.xml
The org.apache.sshd.common.cipher.Cipher interface specifies for update(byte[] buffer, int offset, int length) that length bytes are encrypted or decrypted in-place in the given buffer, starting at the given offset.
The BaseCipher implementation just called javax.crypto.Cipher.update(). That, however, may buffer blocks and not update all data right away. (For instance, AES pipelined implementations may behave that way.) Buffered blocks may be returned/updated in subsequent update() calls. To ensure that really all bytes given are updated, one needs to call doFinal(), which always returns/updates such buffered blocks.
But javax.crypto.Cipher.doFinal() resets the cipher to its initial state. For use in SSH, this is not appropriate: the cipher must be reset not to the initial state but to …
> GH-455: ensure BaseCipher.update() fulfills the contract

- sshd-common/src/main/java/org/apache/sshd/common/util/OsUtils.java
`p` is the property name like `java.vendor`, and this wasn't matching
> Fix Android detection false negative

- pom.xml
- sshd-cli/pom.xml
- sshd-core/pom.xml
- sshd-core/src/test/java/org/apache/sshd/common/compression/CompressionTest.java
- sshd-core/src/test/java/org/apache/sshd/server/auth/AsyncAuthInteractiveTest.java
- sshd-core/src/test/java/org/apache/sshd/server/auth/AsyncAuthTest.java
- sshd-git/pom.xml
- sshd-mina/pom.xml
- sshd-netty/pom.xml
- sshd-scp/pom.xml
- sshd-sftp/pom.xml
- sshd-spring-sftp/pom.xml
The original Jcraft version of the JSch library has not seen updates in over a decade. The current fork with the most active maintenance is the com.github.mwiede:jsch library and it is largely compatible with the original but with secure defaults. It also absorbed the Jzlib implementation in its own code base and eliminated the need to have the extra dependencies.
As this is only a test dependency for this code base I feel adding this update is an improvement.
> Switch uses of JSch library to the com.github.mwiede:jsch fork

- sshd-spring-sftp/src/main/java/org/apache/sshd/sftp/spring/integration/ApacheSshdSftpSessionFactory.java
The condition for starting the sshclient should be whether the client is started, rather than whether it is opened，
> change client start condition in sshd-spring-sftp

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/io/DirectoryScanner.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpClientDirectoryScanner.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/common/SftpHelper.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/common/SftpHelperTest.java
Some SFTP v3 servers do not include the file type flags in the permissions field of an SSH_FXP_NAME record. It this case use the "longname" field to extract this information, if possible.
Also give the SftpClientDirectoryScanner and the DirectoryScanner a flag to make them return not only regular files but also links and other items. (DirectoryScanner already returned links to regular files; SftpClientDirectoryScanner did not.)
Fixes #489.
> sftp readdir: determine file type from longname

- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkED25519PublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkEcdsaPublicKey.java
This fixes a bug where Gerrit Code Review (3.8.2, at least) does not properly admit U2F based SSH keys, and they get rejected mysteriously on authentication.
> Add missing U2F {ed25519,ecdsa}-sk public key equality methods

- sshd-scp/src/main/java/org/apache/sshd/scp/client/DefaultScpClient.java
- sshd-scp/src/main/java/org/apache/sshd/scp/common/ScpHelper.java
Fixes GH-427.
- Ensures that the initial ACK sent upon creating the channel is processed prior to sending the payload stream.
- Channel  IO streams are first closed to trigger EOF prior to handling the exit code.
- `DefaultScpClient.upload(InputStream local, ...)` no longer hits exit status timeout (5 seconds by default) on each invocation.
- This can be observed by running `ScpTest.testStreamsUploadAndDownload`.
> GH-427: Read initial ACK on channel open prior to direct stream upload & close streams prior to exit code handling 

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/AbstractChannel.java
OpenSSH server sends keep-alive requests as channel requests if a channel is open. Handle these channel requests in the "last-resort" channel request handler.
> [SSHD-1237] Handle keep-alive channel requests

- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Session.java
The proposed improvements for Nio2Session class are based on production experience and fixing some corner cases.
- When the buffer fails to be written, mark the corresponding Future as finished exceptionally
- When underlying network infrastructure splits buffer to multiple write chunks, the second and next chunks were written without respect to configured write timeout
- Minor consistency improvement: use better data structure for write queues which honours possibly concurrent access
> Nio2Session improvements

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/SftpModuleProperties.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
Some SFTP servers appear to return sometimes more data than requested. If that happened, it was possible that a downloaded file would be corrupted (size larger than expected, and some duplicated data inside the file).
By default, throw an exception if an SFTP server returns more data than requested. If property SftpModuleProperties.TOLERATE_EXCESS_DATA is set to true on the session or on the channel, discard such excess data and log a warning.
Avoid code duplication; unify SSH_FXP_READ response handling in AbstractSftpClient.
> GH-468: Handle excess data in SFTP read requests

- CHANGES.md
- docs/standards.md
- sshd-core/src/main/java/org/apache/sshd/client/kex/DHGClient.java
- sshd-core/src/main/java/org/apache/sshd/client/kex/DHGEXClient.java
- sshd-core/src/main/java/org/apache/sshd/common/BaseBuilder.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/AbstractDH.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinKEM.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/KeyEncapsulationMethod.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/MontgomeryCurve.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/SNTRUP761.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/XDH.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/dh/AbstractDHKeyExchange.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/main/java/org/apache/sshd/server/kex/DHGEXServer.java
- sshd-core/src/main/java/org/apache/sshd/server/kex/DHGServer.java
This uses a post-quantum key encapsulation method (KEM) to make key exchange future-proof against quantum attacks. It is to be preferred over curve25519-sha256 "when the extra communication size and computational requirements are acceptable."[1] (curve25519-sha256 exchanged 32 bytes where sntrup761x25519-sha512 exchanges 1190 or 1071 bytes.)
This KEX method changes the encoding of the key from 'mpint' to 'string'. To make the handling of the K value more uniform, change it to 'string' everywhere, and convert mpints with the high bit set explicitly by prepending a zero byte.
Separate the digest from MontgomeryCurve; handle combining curves and hashes (and KEMs) in the BuiltinDHFactories instead.
In the BaseBuilder, add "sntrup761x25519-sha512@openssh.com" as first (i.e., preferred) KEX …
> Implement the "sntrup761x25519-sha512@openssh.com" KEX method

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
If client.read() or client.write() throw an exception, the client must be closed.
Fixes #500.
> GH-500: SftpFileSystemProvider: close SftpClient on exception

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/future/HasException.java
- sshd-common/src/main/java/org/apache/sshd/common/future/WithException.java
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientConnectionService.java
- sshd-core/src/main/java/org/apache/sshd/common/future/GlobalRequestFuture.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractConnectionService.java
- sshd-core/src/main/java/org/apache/sshd/core/CoreModuleProperties.java
- sshd-core/src/test/java/org/apache/sshd/KeepAliveTest.java
Switch from a timeout model to the OpenSSH model: fail if there are more than a certain number of heartbeats for which no reply was received yet.
Fixes #461.
> GH-461: Fix heartbeats with wantReply=true

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/SshClient.java
- sshd-core/src/main/java/org/apache/sshd/core/CoreModuleProperties.java
- sshd-core/src/test/java/org/apache/sshd/client/ProxyTest.java
Previous code only parsed the proxy jumps of the initial HostConfigEntry. However, if the last entry in that list has a HostConfigEntry that again has proxy jumps, these additional proxies must be added to the list. And so on.
To guard against proxy cascades with loops we limit the total number of proxies to at most 10. The limit is configurable through property CoreModuleProperties.MAX_PROXY_JUMPS.
Fixes #318.
> GH-318: fix proxyJumps

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/XDH.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/SessionHelper.java
Because all other KEX algorithms treat the secret resulting from the key agreement as "mpint", our key agreements all returned the "mpint" representation of the result of the key agreement.
But sntrup761x25519-sha512 needs the raw 32 bytes of the key agreement (curve25519-sha256).
Add a flag to XDH that determines whether it returns the raw bytes or the "mpint" bytes.
Fixes #525.
> GH-525: Fix sntrup761x25519-sha512

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/cipher/ChaCha20Cipher.java
- sshd-common/src/main/java/org/apache/sshd/common/mac/Poly1305Mac.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/BufferUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/ByteArrayBuffer.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SunJCESecurityProviderRegistrar.java
- sshd-common/src/test/java/org/apache/sshd/common/cipher/BaseCipherTest.java
- sshd-core/src/main/java/org/apache/sshd/common/channel/ChannelAsyncOutputStream.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/SNTRUP761.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/PacketBuffer.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/RawSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/SftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/SftpMessage.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/extensions/helpers/AbstractSftpClientExtension.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystem.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/DefaultSftpClient.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpOutputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpRemotePathChannel.java
A series of performance optimizations:
* Manual optimizations in the ChaCha20-Poly1305 cipher implementation (loop unrolling, use int instead of long where possible, avoid unnecessary method calls).
* Optimize writing ints/longs into buffers.
* Avoid copying buffers if possible. If we prepare an SSH packet buffer, we should avoid copying it later on if possible.
* Streamline SFTP OutputStreams. Give them a transferFrom operation to be able to read directly into an internal buffer, and internally read-ahead into a second buffer while the first one is being sent.
* Add a convenience operation `SftpClient.put()` for uploading.
* Avoid using the AES implementation from Bouncy Castle (typically a Java implementation). Prefer the one from SunJCE, which uses native code.
> Performance optimizations

- .github/workflows/build.yml
- .github/workflows/master-build.yml
- .mvn/maven.config
- CHANGES.md
- README.md
- pom.xml
- sshd-ldap/pom.xml
> Require JDK 17 at build time (fixes #536)

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientUserAuthService.java
- sshd-core/src/test/java/org/apache/sshd/client/auth/pubkey/MultiAuthTest.java
Fix publickey authentication in multi-authentication: if a server is configured with "publickey,password,publickey", a client must authenticate with two different keys. Also, if a publickey authentication fails and the server sends back a list of further acceptable methods that does not contain publickey, then the client must not continue with publickey authentication.
Fixes #533.
> GH-533:  Fix ClientUserAuthService iteration through methods

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/NamedFactory.java
- sshd-common/src/test/java/org/apache/sshd/common/NamedFactoryTest.java
- sshd-core/src/main/java/org/apache/sshd/client/ClientBuilder.java
- sshd-core/src/main/java/org/apache/sshd/common/BaseBuilder.java
- sshd-core/src/main/java/org/apache/sshd/server/ServerBuilder.java
Also give the methods some javadoc.
Note that `ignoreUnsupported ? f.isSupported : true` is the same as `!ignoreUnsupported || f.isSupported()`, but I find the former easier to read and understand.
Fixes #582.
> GH-582: Fix filtering of unsupported algorithms in NamedFactory

- sshd-common/src/main/java/org/apache/sshd/common/util/io/PathUtils.java
In the Android world, there is no concept similar to a home directory.
That is to say `System.getProperty("user.home")` is always `null`.
This PR can guide developer who target Android to add their own home directory implementation by modifying the exception message.
> Add Android-specific exception message when finding user home

- CHANGES.md
- docs/security-providers.md
- sshd-common/src/main/java/org/apache/sshd/common/cipher/BuiltinCiphers.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/loader/openssh/OpenSSHKeyPairResourceParser.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/writer/openssh/OpenSSHKeyPairResourceWriter.java
- sshd-common/src/main/java/org/apache/sshd/common/random/JceRandom.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/AbstractSecurityProviderRegistrar.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityEntityFactory.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityProviderChoice.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityProviderRegistrar.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SecurityUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/SunJCESecurityProviderRegistrar.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/bouncycastle/BouncyCastleEncryptedPrivateKeyInfoDecryptor.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/bouncycastle/BouncyCastleKeyPairResourceParser.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/bouncycastle/BouncyCastleRandomFactory.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/bouncycastle/BouncyCastleSecurityProviderRegistrar.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/EdDSASecurityProviderRegistrar.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/MontgomeryCurve.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/SNTRUP761.java
Decouple the registrar name from the security provider name. Also check whether the BC RandomGenerator exists at all; in BC-FIPS, it doesn't.
> GH-590: Be more careful with Bouncy Castle in FIPS environment

- sshd-common/src/main/java/org/apache/sshd/common/cipher/BuiltinCiphers.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java
* strnup761x25519-sha512 is now an official IANA name
* fix key size of ChaCha20-Poly1305 cipher
> Minor algorithm changes

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/ByteArrayBuffer.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/keys/OpenSSHCertPublicKeyParser.java
- sshd-core/src/test/java/org/apache/sshd/certificates/OpenSSHCertificateParserTest.java
`Buffer.getBytesConsumed()` is broken. It'll return wrong data for buffers created on a slice of an array not starting at zero. Using it in `OpenSSHCertPublicKeyParser ` will return data before the raw certificate in the buffer if that raw certificate is not the first thing in the buffer.
Fix this by adding a `Buffer.getBytesConsumed(int from)` method, and use that in `OpenSSHCertPublicKeyParser`.
Fixes #618.
> GH-618: Fix reading an OpenSshCertificate from a Buffer

- docs/git.md
- sshd-git/src/main/java/org/apache/sshd/git/pack/GitPackCommand.java
- sshd-git/src/main/java/org/apache/sshd/git/pack/GitPackCommandFactory.java
- sshd-git/src/main/java/org/apache/sshd/git/pack/GitPackConfiguration.java
- sshd-git/src/test/java/org/apache/sshd/git/pack/GitPackCommandTest.java
My proposal to close #616 .
I'm open for suggestions for changes to the interface or the naming, but in general I think this would be a very useful thing to have.
> Add interface to configure details of JGit's pack implementation

- CHANGES.md
- docs/standards.md
- pom.xml
- sshd-core/src/main/java/org/apache/sshd/client/kex/DHGClient.java
- sshd-core/src/main/java/org/apache/sshd/common/BaseBuilder.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinKEM.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/CurveSizeIndicator.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/ECDH.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/KeyEncapsulationMethod.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/MLKEM.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/MontgomeryCurve.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/SNTRUP761.java
- sshd-core/src/main/java/org/apache/sshd/common/kex/XDH.java
- sshd-core/src/main/java/org/apache/sshd/server/kex/DHGServer.java
- sshd-core/src/test/java/org/apache/sshd/common/kex/OpenSshMlKemTest.java
- sshd-mina/pom.xml
- sshd-netty/pom.xml
Implement ML-KEM key exchanges; see https://datatracker.ietf.org/doc/html/draft-kampanakis-curdle-ssh-pq-ke-04 .
All three algorithms proposed in that draft RFC are implemented.
Includes an interoperability test for mlkem768x25519-sha256 against OpenSSH 9.9.
Fixes #606.
> ML-KEM key exchanges using Bouncy Castle 1.79

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/ValidateUtils.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpDirEntryIterator.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpIterableDirEntry.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/SftpTest.java
`ValidateUtils.checkNotNullAndNotEmpty(String, ...)` as a side-effect returns the trimmed string!
Add new methods `ValidateUtils.hasContent(String, ...)` that don't do so, and use that instead.
Fixes #628.
> GH-628: Fix reading directories with trailing blanks in the name

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/channel/AsyncCapableClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/ChannelDirectTcpip.java
- sshd-core/src/main/java/org/apache/sshd/client/channel/ChannelSession.java
- sshd-core/src/test/java/org/apache/sshd/common/forward/PortForwardingTest.java
ChannelDirectTcpip gives user code the ability to request a direct-tcpip forward explicitly, without listener on a local port. (Full local port forwarding with a listener on the local port is not implemented in ChannelDirectTcpip but in TcpipClientChannel.)
Complete the implementation to also support the asynchronous asyncIn and asyncOut streams. Factor out the stream setup from ChannelSession into a new intermediary class, and derive ChannelDirectTcpip from that new class. (Basing it on ChannelSession directly would be wrong; the channel would end up with the wrong type and also inherit the setEnv() method.)
Fixes #626.
> GH-626: Enable Streaming.Async for ChannelDirectTcpip

- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/AbstractSftpSubsystemHelper.java
For the method of **writeDirEntry**, the method '**getLongName(f, shortName, options);**' call '**resolveFileAttributes**' to get attrs too. Using the attrs obtained earlier as parameters can reduce the time by half
```
protected void writeDirEntry(
int id, DirectoryHandle dir, Map<String, Path> entries, Buffer buffer,
int index, Path f, String shortName, LinkOption... options)
throws IOException {
boolean followLinks = resolvePathResolutionFollowLinks(SftpConstants.SSH_FXP_READDIR, "", f);
Map<String, ?> attrs = resolveFileAttributes(
f, SftpConstants.SSH_FILEXFER_ATTR_ALL, !followLinks, options);
entries.put(shortName, f);
SftpFileSystemAccessor accessor = getFileSystemAccessor();
ServerSession session = getServerSession();
accessor.putRemoteFileName(this, f, buffer, shortName, true); …
```
> Sftp server ‘ls’ command timeout

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/client/config/hosts/KnownHostEntry.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/AuthorizedKeyEntry.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/KeyUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/OpenSshCertificate.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/PublicKeyEntry.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/PublicKeyEntryResolver.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/SshPublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/UnsupportedSshPublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkED25519PublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkEcdsaPublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java
- sshd-common/src/test/java/org/apache/sshd/client/config/hosts/KnownHostEntryTest.java
- sshd-core/src/main/java/org/apache/sshd/client/keyverifier/KnownHostsServerKeyVerifier.java
- sshd-core/src/test/java/org/apache/sshd/client/keyverifier/KnownHostsServerKeyVerifierTest.java
- sshd-core/src/test/java/org/apache/sshd/client/keyverifier/KnownHostsUnsupportedKeysTest.java
Harden the parser so that it can parse known_host and authorized_key lines with unknown key types. Introduce a new UnsupportedSshPublicKey class to be able to deal with such entries later on when the server host key is compared. (An alternative would have been not to create PublicKeys from known_host lines at all but to serialize the given server key into string form and then just compare against the string from the known_host line. But that is not possible without breaking API...)
Such an UnsupportedSshPublicKey supports getting its key type, its raw key data, its fingerprint, and it can be written into a Buffer.
Fixes #636.
> GH-636: Handle unknown key types in known_hosts

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpPath.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpPathIterator.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/WithFileAttributeCache.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/WithFileAttributes.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpPathImpl.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/AbstractSftpSubsystemHelper.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/server/SftpSubsystem.java
Remote file systems may have a need to cache file attributes on Path instances. A typical use case is iterating over all files in a directory: the directory listing returns paths, but the underlying remote listing operation may also return file attributes for each entry. This is the case in Sftp, but may also occur for other file systems, for instance a file system wrapping Amazon S3.
It would be unfortunate and inefficient if iterating through the paths returned and doing something with the attributes would have to re-fetch the attributes again if they were already available.
By implementing WithFileAttributes on its Paths, a file system can associate file attributes with a path instance, and client code can access them. If a file system also makes its paths implement the second …
> GH-643: provide interfaces for caching file attributes on paths

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/keyverifier/KnownHostsServerKeyVerifier.java
Abstract handling of revoked key so extending classes has an easier way to add functionality when a matching host entry has a 'revoked' marker. 
Fixes #652.
> Abstract revoked key handling in KnownHostsServerKeyVerifier

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/server/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/test/java/org/apache/sshd/common/auth/PublicKeyAuthenticationTest.java
> bugfix: fix cert auth failed bug

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/session/helpers/AbstractSession.java
- sshd-core/src/test/java/org/apache/sshd/client/kex/NegotiationTest.java
- sshd-core/src/test/java/org/apache/sshd/common/mac/EncryptThenMacTest.java
- sshd-core/src/test/java/org/apache/sshd/util/test/CoreTestSupportUtils.java
An AEAD cipher has a built-in MAC, and no extra MAC will be applied. So there is no need to negotiate one.
Fixes #664.
> GH-664: Skip MAC negotiation if an AEAD cipher was negotiated

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Connector.java
- sshd-core/src/main/java/org/apache/sshd/common/io/nio2/Nio2Service.java
- sshd-core/src/test/java/org/apache/sshd/common/io/IoConnectionTest.java
- sshd-mina/src/main/java/org/apache/sshd/mina/MinaConnector.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoAcceptor.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoConnector.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoService.java
- sshd-netty/src/main/java/org/apache/sshd/netty/NettyIoSession.java
IoSessions are created asynchronously through an IoConnector. When an IoConnector is closed, all sessions created through it are also to be closed.
Because session creation is asynchronous, it was possible that a newly created session registered on an already closed IoConnector, and then would never be closed.
Prevent this by forcibly closing any newly created IoSession if the IoConnector is already closed when the new session tries to register with the connector.
Add a test that verifies that the connect future the client code sees does not provide a session but is fulfilled either by an exception or by having been cancelled.
Fixes #663.
> GH-663: Fix a race in IoSession creation

- .github/dependabot.yml
- sshd-mina/pom.xml
- sshd-mina/src/test/java/org/apache/sshd/mina/MinaSessionTest.java
Frankly said I don't quite understand why this even works. The code certainly doesn't compile against 2.2.4: there's a new (abstract) method in interface IoHandler, and our MinaService inherits that but doesn't implement it. Apparently at runtime this can still work as long as the new method isn't called?
(In mina-core 2.2.5, that method will be a default method, and then everything should be totally fine.)
Also tell dependabot to give us only patch version updates for mina-core. We want to keep the minimum requirement at 2.0.X.
> Also test sshd-mina using mina-core 2.2.4

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGES.md
- sshd-scp/src/main/java/org/apache/sshd/scp/server/ScpShell.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/AbstractSftpClient.java
* Fix current directory handling in SCPShell for WinSCP
* Better handle SFTP append in SFTPv3 for buggy servers: send reasonable write offsets
> ScpShell fixes; SFTP append mode for buggy servers

- sshd-osgi/pom.xml
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/sshd/README.md
this `sshd-osgi-*-sources.jar` non-reproducible timestamp (because jar created by `jar` Ant task without predefined `modificationtime`) is the unique issue for 2.14.0 or 2.13.1
2.15.0 has in addition a `org/apache/sshd/client/userKey` file in `sshd-core-2.15.0-reusable-reusable-tests.jar`: I suppose this file is not absolutely necessary in this jar, as it was not there in 2.14.0: you'll need to define what is useful or not
> fix sources.jar Reproducible Builds issue

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/closeable/AbstractCloseable.java
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientSessionImpl.java
Set the state to "closed" before fulfilling the closeFuture.
Fixes #700.
> GH-700: Fix race in AbstractCloseable.doCloseImmediately()

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/forward/ChannelToPortHandler.java
- sshd-core/src/main/java/org/apache/sshd/server/forward/TcpipServerChannel.java
Provide a getter, and in the port handler itself a method to write data directly, without adjusting the channel window.
Fixes #705.
> GH-705: Make ChannelToPortHandler accessible to user code

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/common/channel/AbstractChannel.java
OpenSSH < 5.1p1 (from 2008!) does not handle a success reply and then disconnects after a few keepalives. It really needs a failure reply. Since 5.1p1, OpenSSH can handle both failure and success replies to its keepalive channel messages.
Always return a failure reply if the request is "keepalive@openssh.com".
Fixes #709.
> GH-709: Handle keep-alive channel messages sent by an old OpenSSH server

- CHANGES.md
- sshd-core/src/main/java/org/apache/sshd/client/SshClient.java
If SshClient creates an empty HostConfigEntry, supply the default port if the given port is <= 0.
I'd have liked to do that once and for all in HostConfigEntry.getPort(), but HostConfigEntry.append(Appendable a) relies on getPort() returning a value <= 0 if not set.
If there _is_ a HostConfigEntry for the proxyJump, then HostConfigEntryResolver.resolveEffectiveHost() would already supply the default port. (That bit was fixed in version 2.10.)
Fixes #727.
> GH-727: supply default port for proxyJump if no HostConfigEntry

- CHANGES.md
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpInputStreamAsync.java
- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/impl/SftpRemotePathChannel.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpFileSystemTest.java
Give the SftpInputStreamAsync a logical file size larger than the current position transfer is requested to start at. If the user calls transferTo(position, count, output), the logical file size for the SftpInputStreamAsync should be (position + count). It's no problem if that is larger than the real file size, it'll just produce an EOF return.
Also guard against NPE in SftpInputStreamAsync in case the initial position is beyond the alleged file size.
Fixes #733.
> GH-733: Fix SftpRemotePathChannel.transferTo

- sshd-core/src/main/java/org/apache/sshd/client/session/ClientSession.java
- sshd-core/src/test/java/org/apache/sshd/client/session/ClientSessionTest.java
Added commandTimeoutMillis in executeRemoteCommand
Implemets https://github.com/apache/mina-sshd/issues/725
> [GH-725] Added commandTimeoutMillis in executeRemoteCommand

- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/EdDSASecurityProviderUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/NetI2pCryptoEdDSASupport.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/bouncycastle/BouncyCastleEdDSASupport.java
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/generic/EdDSASupport.java
- sshd-putty/src/main/java/org/apache/sshd/putty/EdDSAPuttyKeyDecoder.java
Using PuttyKeyUtils we can get an error if we don't want dependency net.i2p.crypto but having BC dependency, I made some change using SecurityUtils.getEdDSASupport to remove net.i2p.crypto dependency
> #771 Avoid NoClassDefFoundError: net/i2p/crypto/eddsa/EdDSAPublicKey

- sshd-sftp/src/main/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProvider.java
- sshd-sftp/src/test/java/org/apache/sshd/sftp/client/fs/SftpFileSystemProviderURITest.java
- Allow userinfo without password
- Validate hostname
- Use port 22 as default
Fixes Filesystem Provider with SSH key-based authentication #516
> [GH-516] Fix filesystem-id parsing in getFileSystem(URI)

- sshd-core/src/main/java/org/apache/sshd/client/channel/AbstractClientChannel.java
- sshd-core/src/main/java/org/apache/sshd/client/session/ClientSessionImpl.java
On some hosts, on which waiting for the `futureLock.wait(remWait)` is faster than 1 millisecond, `remWait` gets reduced by 123 milliseconds although not even one passed.
As each host has different cycle times, this happens an unknown amount of times.
This causes a `ClientChannelEvent.Timeout` after a much smaller time passed than the configured timeout.
With these changes, the `remWait` is calculated based on the milliseconds passed instead of transformed nanoseconds.
The same code is found in `ClientSessionImpl@waitFor`. This is also addressed.
> Trigger ClientChannelEvent.Timeout and ClientSessionEvent.TIMEOUT independently to host's program cycle times

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/KeyUtils.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/impl/SkECDSAPublicKeyEntryDecoder.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/impl/SkED25519PublicKeyEntryDecoder.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SecurityKeyPublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkED25519PublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/config/keys/u2f/SkEcdsaPublicKey.java
- sshd-common/src/main/java/org/apache/sshd/common/signature/AbstractSecurityKeySignature.java
Parse the "verify_required" flag from authorized_keys and set it on the keys; add a getter. When checking the signature, also check the "verified" flag if "verified-required" is set.
Fixes #807.
> GH-807: Handle "verified" flag for sk-* keys

- sshd-common/src/main/java/org/apache/sshd/common/signature/AbstractSecurityKeySignature.java
- sshd-core/src/main/java/org/apache/sshd/server/auth/pubkey/AuthorizedKeyEntriesPublickeyAuthenticator.java
- sshd-core/src/main/java/org/apache/sshd/server/auth/pubkey/UserAuthPublicKey.java
- sshd-core/src/test/java/org/apache/sshd/server/auth/AuthorizedKeyEntriesPublickeyAuthenticatorTest.java
- sshd-core/src/test/java/org/apache/sshd/server/auth/UserAuthPublicKeySkTest.java
Respect server-side attributes that may be set in an `authorized_keys` file: `no-touch-required` and `verify-required`. These flags exist _only_ server-side; the public keys received in an SSH_MSG_USERAUTH packet do not have them.
* Ensure that we do _not_ consider these flags when matching public keys received against the `authorized_keys` file.
* Ensure that for signature verification, we _do_ use a key that does carry these flags (i.e., created from the matching `AuthorizedKeyEntry`) so that we can properly check the flags in the signature.
Also throw an exception if there is bogus trailing data after the signature in the packet.
> Fix server-side authentication with FIDO/U2F sk-* keys

- CHANGES.md
- sshd-common/src/main/java/org/apache/sshd/common/util/security/eddsa/SignatureEd25519.java
net.i2p.crypto:eddsa:0.3.0 has a bug and omits a crucial check in signature verification. This was reported as CVE-2020-36843[1] (signature malleability).
The problem affects signature verification, but luckily the missing check can also be performed outside of the library. With this commit we do so and verify that the second 32 bytes of the signature is actually in the range [0..L), with L the order as given in RFC 7748.[2]
This means that the use of net.i2p.crypto:eddsa:0.3.0, if used for ed25519 signatures via Apache MINA SSHD, is safe and **not** subject of CVE-2020-36843. Of course, vulnerability scanners will still report the vulnerability.
Note that Apache MINA SSHD has only a completely optional dependency on net.i2p.crypto:eddsa:0.3.0. If that artifact is not present in the …
> SignatureEd25519: fix vulnerability in net.i2p.crypto:eddsa:0.3.0
